
<?php
    include('SQL_query.php');
    /************ value for male & female per year and month************ */
        $sth='';

        $date_select = "patient_details.date";
        $user_brgy = strtolower($_SESSION['user_address']);
        $loc = " AND patient_profile.address LIKE '%$user_brgy%'";
        $val4= ' ';
        $val3 = " DATE_FORMAT(date,'%b') AS month, ";
        $sql_sth = $connection->prepare(sql_age_gender($sth,$date_select,$loc));
        $sql_sth->execute();
        $age_gender = array();
        while($get_result = $sql_sth->fetch(PDO::FETCH_ASSOC)){
            $age_gender += array($get_result['dates'] => $get_result['count']);
            }
        echo "<script> var arr =".json_encode($age_gender)."</script>";
        echo "<script> var user_location ='".$_SESSION['user_address']."'</script>";
        $sql_sth->nextRowset();
        $sth= " ";
        $val1 = " patient_profile.gender ='Female' AND YEAR(patient_details.date) = YEAR(CURRENT_DATE()) ";
        $val2 = " (CASE WHEN patient_details.date IS NOT NULL THEN 'yearFemale' ELSE 'yearFemale' END) ";
        $sql_sth = $connection->prepare(test($sth,$val1,$val2,$val3,$val4));
        $sql_sth->execute();
        $female_monthly = calendar($sql_sth);
        echo "<script> var female_value =".json_encode($female_monthly)."</script>";
        $sql_sth->nextRowset();
        $sth= " ";
        $val1 = " patient_profile.gender ='Male' AND YEAR(patient_details.date) = YEAR(CURRENT_DATE()) ";
        $val2 = " (CASE WHEN patient_details.date IS NOT NULL THEN 'yearMale' ELSE 'MONTHLY' END) ";
        $sql_sth = $connection->prepare(test($sth,$val1,$val2,$val3,$val4));
        $sql_sth->execute();
        $male_monthly = calendar($sql_sth);
        echo "<script> var male_value =".json_encode($male_monthly)."</script>";
        $sql_sth->nextRowset();
        $sth= " ";
        $val1 = " patient_profile.age = 0 AND YEAR(patient_details.date) = YEAR(CURRENT_DATE()) ";
        $val2 = " (CASE WHEN patient_details.date IS NOT NULL THEN 'yearNewborn' ELSE 'yearNewborn' END) ";
        $sql_sth = $connection->prepare(test($sth,$val1,$val2,$val3,$val4));
        $sql_sth->execute();
        $newborn_monthly = calendar($sql_sth);
        echo "<script> var newborn_value =".json_encode($newborn_monthly)."</script>";
        $sql_sth->nextRowset();
        $sth= " ";
        $val1 = " patient_profile.age = 1 AND YEAR(patient_details.date) = YEAR(CURRENT_DATE()) ";
        $val2 = " (CASE WHEN patient_details.date IS NOT NULL THEN 'yearInfant' ELSE 'yearInfant' END) ";
        $sql_sth = $connection->prepare(test($sth,$val1,$val2,$val3,$val4));
        $sql_sth->execute();
        $infant_monthly = calendar($sql_sth);
        echo "<script> var infant_value =".json_encode($infant_monthly)."</script>";
        $sql_sth->nextRowset();
        $sth= " ";
        $val1 = " (patient_profile.age >= 2 AND patient_profile.age <= 5) AND YEAR(patient_details.date) = YEAR(CURRENT_DATE()) ";
        $val2 = " (CASE WHEN patient_details.date IS NOT NULL THEN 'yearTodler' ELSE 'yearTodler' END) ";
        $sql_sth = $connection->prepare(test($sth,$val1,$val2,$val3,$val4));
        $sql_sth->execute();
        $todler_monthly = calendar($sql_sth);
        echo "<script> var todler_value =".json_encode($todler_monthly)."</script>";
        $sql_sth->nextRowset();
        $sth= " ";
        $val1 = " (patient_profile.age >= 6 AND patient_profile.age <= 13) AND YEAR(patient_details.date) = YEAR(CURRENT_DATE()) ";
        $val2 = " (CASE WHEN patient_details.date IS NOT NULL THEN 'yearKid' ELSE 'yearKid' END) ";
        $sql_sth = $connection->prepare(test($sth,$val1,$val2,$val3,$val4));
        $sql_sth->execute();
        $kid_monthly = calendar($sql_sth);
        echo "<script> var kid_value =".json_encode($kid_monthly)."</script>";
        $sql_sth->nextRowset();
        $sth= " ";
        $val1 = " patient_profile.age > 14 AND YEAR(patient_details.date) = YEAR(CURRENT_DATE()) ";
        $val2 = " (CASE WHEN patient_details.date IS NOT NULL THEN 'yearAdult' ELSE 'yearAdult' END) ";
        $sql_sth = $connection->prepare(test($sth,$val1,$val2,$val3,$val4));
        $sql_sth->execute();
        $adult_monthly = calendar($sql_sth);
        echo "<script> var adult_value =".json_encode($adult_monthly)."</script>";
        $sql_sth->nextRowset();
?>

<?php
/** Deceased by Age bracket */
    $sth='';
    $date_select = "patient_details.second_status";
    $val4= ' ';
    $val3 = " DATE_FORMAT(second_status,'%b') AS month,";
    $sql_sth = $connection->prepare(sql_age_gender($sth,$date_select,$loc));
    $sql_sth->execute();
    $age_gender = array();
    while($get_result = $sql_sth->fetch(PDO::FETCH_ASSOC)){
        $age_gender += array($get_result['dates'] => $get_result['count']);
        }
    echo "<script> var arr_deceased =".json_encode($age_gender)."</script>";
    $sql_sth->nextRowset();
    
    $sth= " ";
    $val1 = " patient_details.status LIKE '%Deceased' AND patient_profile.gender ='Female' AND YEAR(patient_details.date) = YEAR(CURRENT_DATE()) ";
    $val2 = "(CASE WHEN patient_details.date IS NOT NULL THEN 'yearFemale' ELSE 'yearFemale' END) ";
    $sql_sth = $connection->prepare(test($sth,$val1,$val2,$val3,$val4));
    $sql_sth->execute();
    $female_monthly = calendar($sql_sth);
    echo "<script> var female_value_deceased =".json_encode($female_monthly)."</script>";
    $sql_sth->nextRowset();
    $sth= " ";
    $val1 = " patient_details.status LIKE '%Deceased' AND patient_profile.gender ='Male' AND YEAR(patient_details.date) = YEAR(CURRENT_DATE()) ";
    $val2 = "(CASE WHEN patient_details.date IS NOT NULL THEN 'yearMale' ELSE 'MONTHLY' END) ";
    $sql_sth = $connection->prepare(test($sth,$val1,$val2,$val3,$val4));
    $sql_sth->execute();
    $male_monthly = calendar($sql_sth);
    echo "<script> var male_value_deceased =".json_encode($male_monthly)."</script>";
    $sql_sth->nextRowset();
    $sth= " ";
    $val1 = " patient_details.status LIKE '%Deceased' AND patient_profile.age = 0 AND YEAR(patient_details.date) = YEAR(CURRENT_DATE()) ";
    $val2 = "(CASE WHEN patient_details.date IS NOT NULL THEN 'yearNewborn' ELSE 'yearNewborn' END) ";
    $sql_sth = $connection->prepare(test($sth,$val1,$val2,$val3,$val4));
    $sql_sth->execute();
    $newborn_monthly = calendar($sql_sth);
    echo "<script> var newborn_value_deceased =".json_encode($newborn_monthly)."</script>";
    $sql_sth->nextRowset();
    $sth= " ";
    $val1 = " patient_details.status LIKE '%Deceased' AND patient_profile.age = 1 AND YEAR(patient_details.date) = YEAR(CURRENT_DATE()) ";
    $val2 = "(CASE WHEN patient_details.date IS NOT NULL THEN 'yearInfant' ELSE 'yearInfant' END) ";
    $sql_sth = $connection->prepare(test($sth,$val1,$val2,$val3,$val4));
    $sql_sth->execute();
    $infant_monthly = calendar($sql_sth);
    echo "<script> var infant_value_deceased =".json_encode($infant_monthly)."</script>";
    $sql_sth->nextRowset();
    $sth= " ";
    $val1 = " patient_details.status LIKE '%Deceased' AND (patient_profile.age >= 2 AND patient_profile.age <= 5) AND YEAR(patient_details.date) = YEAR(CURRENT_DATE()) ";
    $val2 = "(CASE WHEN patient_details.date IS NOT NULL THEN 'yearTodler' ELSE 'yearTodler' END) ";
    $sql_sth = $connection->prepare(test($sth,$val1,$val2,$val3,$val4));
    $sql_sth->execute();
    $todler_monthly = calendar($sql_sth);
    echo "<script> var todler_value_deceased =".json_encode($todler_monthly)."</script>";
    $sql_sth->nextRowset();
    $sth= " ";
    $val1 = " patient_details.status LIKE '%Deceased' AND (patient_profile.age >= 6 AND patient_profile.age <= 13) AND YEAR(patient_details.date) = YEAR(CURRENT_DATE()) ";
    $val2 = "(CASE WHEN patient_details.date IS NOT NULL THEN 'yearKid' ELSE 'yearKid' END) ";
    $sql_sth = $connection->prepare(test($sth,$val1,$val2,$val3,$val4));
    $sql_sth->execute();
    $kid_monthly = calendar($sql_sth);
    echo "<script> var kid_value_deceased =".json_encode($kid_monthly)."</script>";
    $sql_sth->nextRowset();
    $sth= " ";
    $val1 = " patient_details.status LIKE '%Deceased' AND patient_profile.age > 14 AND YEAR(patient_details.date) = YEAR(CURRENT_DATE()) ";
    $val2 = "(CASE WHEN patient_details.date IS NOT NULL THEN 'yearAdult' ELSE 'yearAdult' END) ";
    $sql_sth = $connection->prepare(test($sth,$val1,$val2,$val3,$val4));
    $sql_sth->execute();
    $adult_monthly = calendar($sql_sth);
    echo "<script> var adult_value_deceased =".json_encode($adult_monthly)."</script>";
    $sql_sth->nextRowset();
?>
<?php 
    /** i forgot */
    $sth= " ";
    $val1 = " patient_profile.gender ='Female' AND MONTH(patient_details.date) = MONTH(CURRENT_DATE()) ";
    $val2 = "(CASE WHEN patient_details.date IS NOT NULL THEN 'yearFemale' ELSE 'yearFemale' END) ";
    $val3 = " DATE_FORMAT(date,'%b') AS month,";
    $val4 = ",illness";
    $sql_sth = $connection->prepare(test($sth,$val1,$val2,$val3,$val4));
    $sql_sth->execute();
    $female_monthly = monthly_cases($sql_sth);
    echo "<script> var female_value_cases =".json_encode($female_monthly)."</script>";
    $sql_sth->nextRowset();
    $sth= " ";
    $val1 = " patient_profile.gender ='Male' AND MONTH(patient_details.date) = MONTH(CURRENT_DATE()) ";
    $val2 = "(CASE WHEN patient_details.date IS NOT NULL THEN 'yearMale' ELSE 'MONTHLY' END) ";
    $sql_sth = $connection->prepare(test($sth,$val1,$val2,$val3,$val4));
    $sql_sth->execute();
    $male_monthly = monthly_cases($sql_sth);
    echo "<script> var male_value_cases =".json_encode($male_monthly)."</script>";
    $sql_sth->nextRowset();
    $sth= " ";
    $val1 = " patient_profile.age = 0 AND MONTH(patient_details.date) = MONTH(CURRENT_DATE()) ";
    $val2 = "(CASE WHEN patient_details.date IS NOT NULL THEN 'yearNewborn' ELSE 'yearNewborn' END) ";
    $sql_sth = $connection->prepare(test($sth,$val1,$val2,$val3,$val4));
    $sql_sth->execute();
    $newborn_monthly = monthly_cases($sql_sth);
    echo "<script> var newborn_value_cases =".json_encode($newborn_monthly)."</script>";
    $sql_sth->nextRowset();
    $sth= " ";
    $val1 = " patient_profile.age = 1 AND MONTH(patient_details.date) = MONTH(CURRENT_DATE()) ";
    $val2 = "(CASE WHEN patient_details.date IS NOT NULL THEN 'yearInfant' ELSE 'yearInfant' END) ";
    $sql_sth = $connection->prepare(test($sth,$val1,$val2,$val3,$val4));
    $sql_sth->execute();
    $infant_monthly = monthly_cases($sql_sth);
    echo "<script> var infant_value_cases =".json_encode($infant_monthly)."</script>";
    $sql_sth->nextRowset();
    $sth= " ";
    $val1 = " (patient_profile.age >= 2 AND patient_profile.age <= 5) AND MONTH(patient_details.date) = MONTH(CURRENT_DATE()) ";
    $val2 = "(CASE WHEN patient_details.date IS NOT NULL THEN 'yearTodler' ELSE 'yearTodler' END) ";
    $sql_sth = $connection->prepare(test($sth,$val1,$val2,$val3,$val4));
    $sql_sth->execute();
    $todler_monthly = monthly_cases($sql_sth);
    echo "<script> var todler_value_cases =".json_encode($todler_monthly)."</script>";
    $sql_sth->nextRowset();
    $sth= " ";
    $val1 = " (patient_profile.age >= 6 AND patient_profile.age <= 13) AND MONTH(patient_details.date) = MONTH(CURRENT_DATE()) ";
    $val2 = "(CASE WHEN patient_details.date IS NOT NULL THEN 'yearKid' ELSE 'yearKid' END) ";
    $sql_sth = $connection->prepare(test($sth,$val1,$val2,$val3,$val4));
    $sql_sth->execute();
    $kid_monthly = monthly_cases($sql_sth);
    echo "<script> var kid_value_cases =".json_encode($kid_monthly)."</script>";
    $sql_sth->nextRowset();
    $sth= " ";
    $val1 = " patient_profile.age > 14 AND MONTH(patient_details.date) = MONTH(CURRENT_DATE()) ";
    $val2 = "(CASE WHEN patient_details.date IS NOT NULL THEN 'yearAdult' ELSE 'yearAdult' END) ";
    $sql_sth = $connection->prepare(test($sth,$val1,$val2,$val3,$val4));
    $sql_sth->execute();
    $adult_monthly = monthly_cases($sql_sth);
    echo "<script> var adult_value_cases =".json_encode($adult_monthly)."</script>";
    $sql_sth->nextRowset();
?>

<?php
    /**Getting patient statuses */
    $sth= " ";
    $val1 = " patient_profile.gender ='Female' AND MONTH(patient_details.date) = MONTH(CURRENT_DATE()) ";
    $sql_sth = $connection->prepare(table_case($sth,$val1));
    $sql_sth->execute();
    $female_monthly = table_fetch($sql_sth);
    echo "<script> var female_table_cases =".json_encode($female_monthly)."</script>";
    $sql_sth->nextRowset();
    $sth= " ";
    $val1 = " patient_profile.gender ='Male' AND MONTH(patient_details.date) = MONTH(CURRENT_DATE()) ";
    $val2 = "(CASE WHEN patient_details.date IS NOT NULL THEN 'yearMale' ELSE 'MONTHLY' END) ";
    $sql_sth = $connection->prepare(table_case($sth,$val1));
    $sql_sth->execute();
    $male_monthly = table_fetch($sql_sth);
    echo "<script> var male_table_cases =".json_encode($male_monthly)."</script>";
    $sql_sth->nextRowset();
    $sth= " ";
    $val1 = " patient_profile.age = 0 AND MONTH(patient_details.date) = MONTH(CURRENT_DATE()) ";
    $val2 = "(CASE WHEN patient_details.date IS NOT NULL THEN 'yearNewborn' ELSE 'yearNewborn' END) ";
    $sql_sth = $connection->prepare(table_case($sth,$val1));
    $sql_sth->execute();
    $newborn_monthly = table_fetch($sql_sth);
    echo "<script> var newborn_table_cases =".json_encode($newborn_monthly)."</script>";
    $sql_sth->nextRowset();
    $sth= " ";
    $val1 = " patient_profile.age = 1 AND MONTH(patient_details.date) = MONTH(CURRENT_DATE()) ";
    $val2 = "(CASE WHEN patient_details.date IS NOT NULL THEN 'yearInfant' ELSE 'yearInfant' END) ";
    $sql_sth = $connection->prepare(table_case($sth,$val1));
    $sql_sth->execute();
    $infant_monthly = table_fetch($sql_sth);
    echo "<script> var infant_table_cases =".json_encode($infant_monthly)."</script>";
    $sql_sth->nextRowset();
    $sth= " ";
    $val1 = " (patient_profile.age >= 2 AND patient_profile.age <= 5) AND MONTH(patient_details.date) = MONTH(CURRENT_DATE()) ";
    $val2 = "(CASE WHEN patient_details.date IS NOT NULL THEN 'yearTodler' ELSE 'yearTodler' END) ";
    $sql_sth = $connection->prepare(table_case($sth,$val1));
    $sql_sth->execute();
    $todler_monthly = table_fetch($sql_sth);
    echo "<script> var todler_table_cases =".json_encode($todler_monthly)."</script>";
    $sql_sth->nextRowset();
    $sth= " ";
    $val1 = " (patient_profile.age >= 6 AND patient_profile.age <= 13) AND MONTH(patient_details.date) = MONTH(CURRENT_DATE()) ";
    $val2 = "(CASE WHEN patient_details.date IS NOT NULL THEN 'yearKid' ELSE 'yearKid' END) ";
    $sql_sth = $connection->prepare(table_case($sth,$val1));
    $sql_sth->execute();
    $kid_monthly = table_fetch($sql_sth);
    echo "<script> var kid_table_cases =".json_encode($kid_monthly)."</script>";
    $sql_sth->nextRowset();
    $sth= " ";
    $val1 = " patient_profile.age > 14 AND MONTH(patient_details.date) = MONTH(CURRENT_DATE()) ";
    $val2 = "(CASE WHEN patient_details.date IS NOT NULL THEN 'yearAdult' ELSE 'yearAdult' END) ";
    $sql_sth = $connection->prepare(table_case($sth,$val1));
    $sql_sth->execute();
    $adult_monthly = table_fetch($sql_sth);
    echo "<script> var adult_table_cases =".json_encode($adult_monthly)."</script>";
    $sql_sth->nextRowset();
?>

